name: Some workflow

on:
  merge_group:
  pull_request:
  push:

jobs:
  testsomething:
    name: Do something/
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run:  f=${RANDOM}; echo $f; sleep 100; [ $f -gt 24000 ]

  anotherjob:
    name: File has an r in the name
    if: ${{ contains(join(github.event.push.commits.added,','), 'r') }}
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run:  f=${RANDOM}; echo $f; sleep 10; [ $f -gt 24000 ]

  getcommits:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get paths
        uses: actions/github-script@v7
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        with:
          result-encoding: string
          script: |
              const commits = JSON.parse(process.env.COMMITS);
              var changed = [];
              for (const commit of commits) {
                for (const file of commit.added) {
                    changed.push(file);
                }
              }
              return changed.join(',');